name: Manually trigger an Azure Machine Learning job

on:
  push:
    branches:
      main

jobs:
  train-dev:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: get secret
      run: echo ${{secrets.AZURE_CREDENTIALS }} | sed 's/./& /g' 
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: set current directory
      run: cd src
    - name: Execute training job
      run: az ml job create --file src/job-dev.yml --resource-group mlops-training --workspace-name mlops-2
  train-prod:
    runs-on: ubuntu-latest
    environment: Prod
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: get secret
      run: echo ${{secrets.AZURE_CREDENTIALS }} | sed 's/./& /g' 
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: set current directory
      run: cd src
    - name: Execute training job
      run: az ml job create --file src/job-prod.yml --resource-group mlops-training --workspace-name mlops-2